import sys, pygame
from func import *
pygame.init()

REAL_WIDTH = int(get_value("width", "1200"))
REAL_HEIGHT = int(get_value("height", "900"))
W_LIMIT = (REAL_WIDTH/REAL_HEIGHT) > (16/9)
WINDOW_WIDTH = (REAL_HEIGHT*(16/9) if W_LIMIT else REAL_WIDTH)
WINDOW_HEIGHT = REAL_HEIGHT
X_OFFSET = ((REAL_WIDTH-WINDOW_WIDTH)/2 if W_LIMIT else 0)
LINE_WIDTH = 5.76 * WINDOW_HEIGHT
LINE_HEIGHT = 0.0075 * WINDOW_HEIGHT
X = WINDOW_WIDTH * 0.05625
Y = WINDOW_HEIGHT * 0.6
NOTE_WIDTH = WINDOW_WIDTH * 0.123
NOTE_SCALE = NOTE_WIDTH / 989
HOLD_YSCALE = 1 / 1900
HOLD_HL_YSCALE = 1 / 1854
HOLD_HL_SCALE = NOTE_WIDTH / 966
LINE_COLOR = (0.996, 1, 0.663)
HIT_COLOR = (1, 0.925, 0.627)
HIT_WIDTH = NOTE_WIDTH * 1.576
HIT_SCALE = HIT_WIDTH / 256
PARTICLE_COLOR = HIT_COLOR
WIDTH_SCALE = WINDOW_WIDTH / 800
HEIGHT_SCALE = WINDOW_HEIGHT / 600
PARTICLE_SIZE = 17.5 * WIDTH_SCALE
RPE_LINE_WIDTH = WINDOW_WIDTH * (4000 / 1350)
RPE_LINE_HEIGHT = WINDOW_HEIGHT * (5 / 900)
RPE_LINE_COLOR = [0.996, 1, 0.663]
FONT_SIZE = 75
FONT = pygame.font.Font(".\\Resources\\fonts\\font.ttf", FONT_SIZE)
TEXT_HEIGHT = WINDOW_HEIGHT * 0.0484#0.0555
TEXT_SCALE = TEXT_HEIGHT / FONT_SIZE
if "--render" in sys.argv:
    PAINT_SPACE = 0
else:
    PAINT_SPACE = 0.02
LINE_TEXTURE_SCALE = WINDOW_WIDTH / 1350
RPE_TEXTURE_COLOR = [1, 1, 1]
RPE_TEXT_COLOR = [1, 1, 1]
CAPTION = "PyPhiRenderer"
LAUNCHER_WIDTH = 1200
LAUNCHER_HEIGHT = 900
RESOURCE_PATH = get_value("resource", ".\\Resources")